import type { Metadata } from "next";
import AuthSession from "@/components/AuthSession";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body>
        <AuthSession />
        {children}
      </body>
    </html>
  );
}
